# Generated by Django 5.0.1 on 2024-06-14 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_alter_chatroom_members_alter_chatroom_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="chatrooms", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
