# Generated by Django 5.0.1 on 2024-06-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_chatroom_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="type",
            field=models.CharField(
                choices=[("G", "Group"), ("D", "Direct Room")],
                default="G",
                max_length=5,
            ),
        ),
    ]
